### PR TITLE
fix!: always assign a trace ID to each request

### LINKED ISSUE #1025: getCurrentContextId() returns null when not sampling
I am trying to use `LogEntry.trace` as a correlation identifier to tie different log messages together. I wasn't sure if this would be a good idea, but I got some confirmation from [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#FIELDS.trace_sampled):

> A non-sampled `trace` value is still useful as a request correlation identifier.

Being able to click on "Show matching entries" in the log view seems like a really useful thing to have:

Screenshot 2019-05-13 at 20 33 18

The Bunyan logging wrapper uses the [`agent.getCurrentContextId()`](https://github.com/googleapis/nodejs-logging-bunyan/blob/d451b937139e5906ff66819788af6245256c08aa/src/index.ts#L44-L66). The problem is that `getCurrentContextId()` only seems to return a value if the current request is being sampled, and `null` otherwise.

Is this intended? Would it be possible to still return a traceId from `getCurrentContextId()` or perhaps expose another function to do this, for the sake of logging the trace id, to be able to correlate log entries.

### PR DESCRIPTION
**Pull request by kjin**
Fixes #1025

We already store untraced requests (via a single object representing ALL untraced requests) in CLS, this changes it so that these objects also have a trace ID (and span ID, though not sure if it is useful).

### CODE REVIEW

**Comment by kjin** [comment]
Actually, marking this as WIP (don't review) while I figure out what to do when we call `Tracer#createChildSpan`.

File: src/span-data.ts [hunk 1]
```diff
@@ -236,10 +277,9 @@ export const UNCORRELATED_CHILD_SPAN = createPhantomSpanData(
 
 /**
  * A virtual trace span that indicates that a real child span couldn't be
- * created because the corresponding root span was disallowed by user
- * configuration.
+ * created because the Trace Agent was disabled.
  */
-export const UNTRACED_CHILD_SPAN = createPhantomSpanData(SpanType.UNTRACED);
+export const DISABLED_CHILD_SPAN = createPhantomSpanData(SpanType.UNTRACED);
```
Comment (ofrobots) [inline src/span-data.ts]: This is going to sound nit-picky...

Is there a reason why the concept was renamed on the left hand side but left the same on the right hand side?

Based on your decision to rename the export, it seems that you prefer external users to conceptually think about this concept as `disabled`. If that is the right conceptualization, why is not the right conceptualization for the internals in this file?

Comment (kjin) [reply src/span-data.ts]: The variable formerly named `UNTRACED_CHILD_SPAN` is now only used when the Trace Agent is disabled which is why the LHS changed (where as before it is used for a disabled agent or for unsampled traces). As for the RHS, there continues to be multiple reasons for a span object to represent "untraced" work -- either unsampled, or disabled.

I could get behind the idea that we could just introduce `UNSAMPLED` and `DISABLED` in place of `UNTRACED`, though.

Comment (ofrobots) [reply src/span-data.ts]: +1 on the rename. I won't block this PR, but conceptual clarity is important.
